### ISSUE TITLE
LTL formulas

### ISSUE THREAD

**Issue by fkgl** [fpom/zinc#3]
Hi sir,
Please, is it possible to use LTL formulas with zinc or no ? if no, please suggest me a useful tool which I can use (for neco I could not install it).

Best regards,
Thank's

**Comment by fpom** [comment]
So far, no. It's planned but I lack time to develop Zinc. However, you may look at Spot: it has a Python interface and it should be reasonably easy to make a model-checker that uses Zinc to enumerate the states, and Spot to perform the model-checking.
